card_image: ''
created_at: 2025-02-18 01:47:20.701000
creator_id: unknown
deployment:
  last_deployed: null
  type: null
  url: ''
description: Pixel-perfect slides with interactive demos
domain: ''
features:
- ''
getting_started_screen: false
getting_started_screen_index: 0
git:
  branch: main
  remote: origin
  url: https://github.com/davidvgilmore/memex-slidev
hero_image: ''
icon: ''
is_published: true
pills:
- icon: ''
  label: ''
  prompt: ''
project_id: xSd6O0c73p0N9uZU8bY7
published_at: 2025-02-18 07:57:13.269000
requirements:
- description: ''
  type: ''
slug: create-slides
storage:
  compression_enabled: null
  gcs_path: null
  last_sync: null
  max_file_size_mb: null
  size_bytes: null
title: Create slides
tools:
- name: ''
  role: ''
  type: ''
  version: ''
updated_at: 2025-02-18 01:57:13.269000
